name: Build & Deploy to Pages

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  APP_FOLDER: "calories-tracker"

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout
      uses: actions/checkout@v7.0.1
     
    - name: Cache npm dependencies
      uses: actions/cache@v6.1.0
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm
    
    - name: Install dependencies
      run: npm ci

    - name: Setup Doppler CLI
      uses: dopplerhq/cli-action@v4

    - name: Build
      env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_SVC_TOKEN }}
      run: doppler run --project calories-tracker --config prd -- npm run build

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v5.0.0
      with:
        path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v5.0.1

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
